quarkus.http.port=8030
quarkus.http.test-port=8889

openai.async=true
openai.batch.size=50
openai.model=text-embedding-3-small
openai.api.key=change-me
pinecone.api.key=change-me
pinecone.index.url=https://pinecone.io

quarkus.log.level=INFO

quarkus.console.color=false
quarkus.log.console.enable=true
quarkus.log.console.json=false
quarkus.log.console.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-7p [%-19t] %.-20c{1.} [%X] - %s%e%n

quarkus.log.file.enable=true
quarkus.log.file.json=false
quarkus.log.file.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-7p [%-19t] %.-20c{1.} [%X] - %s%e%n
quarkus.log.file.path=logs/quarkus.log
quarkus.log.file.rotation.rotate-on-boot=false
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=2
quarkus.log.file.rotation.file-suffix=yyyy-MM-dd


